analytics: UA-46982122-1
canonical: http://canary.occupywallst.org
debug: false
disqus: occupywallst
email: support@occupywallst.org
googleplus: OccupyWallStreet
host: www.occupywallst.org
lang: en
name: Occupy Wall Street
twitter: OccupyWallSt

# Jekyll Settings
encoding: UTF-8
excerpt_separator: "\n\n"
exclude:
  - Makefile
markdown: redcarpet
redcarpet:
  extensions:
    - footnotes
    - smart
    - space_after_headers
    - space_after_headers
    - strikethrough
    - superscript
permalink: none
pygments: true
timezone: America/New_York
